# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.187.0/containers/javascript-node/.devcontainer/base.Dockerfile

# [Choice] Node.js version: 18, 16, 14
ARG VARIANT="18-buster"
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIANT}

# Install extra tools for CAP development & deployment.
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends curl git jq 

ENV NPM_CONFIG_PREFIX=/home/node/.npm
ENV PATH=$NPM_CONFIG_PREFIX/bin:$PATH

#FOR LOCAL DEV BUILDS ONLY
RUN su node -c "npm config set proxy <your_proxy_here>"
RUN su node -c "npm config set https-proxy <your_proxy_here>"
RUN su node -c "npm config set strict-ssl false"


# Install SAP CAP SDK globally
RUN su node -c "npm install -g @sap/cds-dk"


RUN su node -c "cds -v"
RUN /bin/bash -c echo 'service CatalogService { entity Books { key ID: UUID; } }' \    > services.cds
#ENTRYPOINT  su node -c "cds watch"
ENTRYPOINT ["tail", "-f", "/dev/null"]


